[tool.poetry]
name = "nautobot-docker-compose"
version = "0.1.1"
description = ""
authors = ["John Doe <johndoe@mail.com>"]

[tool.poetry.dependencies]
python = "<3.13,>=3.9.2"

# nautobot-example-plugin = {path = "plugins/plugin_example", develop = true}
nautobot-ssot = "^3.9.0"
nautobot = "2.4.10"
nautobot-floor-plan = "^2.8.1"
nautobot-data-validation-engine = "^3.2.0"
nautobot-bgp-models = "^2.3.1"
nautobot-design-builder = "^2.2.0"
nautobot-plugin-nornir = "^2.2.1"
nautobot-golden-config = "^2.4.1"
nautobot-device-lifecycle-mgmt = "^3.1.1"
nautobot-device-onboarding = "^4.2.5"
nautobot-secrets-providers = "^3.2.0"


[tool.poetry.dev-dependencies]
invoke = "*"
toml = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
