[project]
name = "nautobot-docker-compose"
version = "0.1.1"
description = ""
authors = [{ name = "John Doe", email = "johndoe@mail.com" }]
requires-python = ">=3.9,<3.13"
dependencies = ["nautobot==2.3.6"]

[dependency-groups]
dev = [
    "invoke",
    "toml",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
